// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package address.proxies;

public class District
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject districtMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Address.District";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DistrictCode("DistrictCode"),
		District("District"),
		IsActive("IsActive"),
		District_Province("Address.District_Province");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public District(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Address.District"));
	}

	protected District(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject districtMendixObject)
	{
		if (districtMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Address.District", districtMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Address.District");

		this.districtMendixObject = districtMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'District.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static address.proxies.District initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return address.proxies.District.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static address.proxies.District initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new address.proxies.District(context, mendixObject);
	}

	public static address.proxies.District load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return address.proxies.District.initialize(context, mendixObject);
	}

	public static java.util.List<address.proxies.District> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<address.proxies.District> result = new java.util.ArrayList<address.proxies.District>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Address.District" + xpathConstraint))
			result.add(address.proxies.District.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DistrictCode
	 */
	public final java.lang.String getDistrictCode()
	{
		return getDistrictCode(getContext());
	}

	/**
	 * @param context
	 * @return value of DistrictCode
	 */
	public final java.lang.String getDistrictCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DistrictCode.toString());
	}

	/**
	 * Set value of DistrictCode
	 * @param districtcode
	 */
	public final void setDistrictCode(java.lang.String districtcode)
	{
		setDistrictCode(getContext(), districtcode);
	}

	/**
	 * Set value of DistrictCode
	 * @param context
	 * @param districtcode
	 */
	public final void setDistrictCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String districtcode)
	{
		getMendixObject().setValue(context, MemberNames.DistrictCode.toString(), districtcode);
	}

	/**
	 * @return value of District
	 */
	public final java.lang.String getDistrict()
	{
		return getDistrict(getContext());
	}

	/**
	 * @param context
	 * @return value of District
	 */
	public final java.lang.String getDistrict(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.District.toString());
	}

	/**
	 * Set value of District
	 * @param district
	 */
	public final void setDistrict(java.lang.String district)
	{
		setDistrict(getContext(), district);
	}

	/**
	 * Set value of District
	 * @param context
	 * @param district
	 */
	public final void setDistrict(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String district)
	{
		getMendixObject().setValue(context, MemberNames.District.toString(), district);
	}

	/**
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive()
	{
		return getIsActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActive.toString());
	}

	/**
	 * Set value of IsActive
	 * @param isactive
	 */
	public final void setIsActive(java.lang.Boolean isactive)
	{
		setIsActive(getContext(), isactive);
	}

	/**
	 * Set value of IsActive
	 * @param context
	 * @param isactive
	 */
	public final void setIsActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.IsActive.toString(), isactive);
	}

	/**
	 * @return value of District_Province
	 */
	public final address.proxies.Province getDistrict_Province() throws com.mendix.core.CoreException
	{
		return getDistrict_Province(getContext());
	}

	/**
	 * @param context
	 * @return value of District_Province
	 */
	public final address.proxies.Province getDistrict_Province(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		address.proxies.Province result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.District_Province.toString());
		if (identifier != null)
			result = address.proxies.Province.load(context, identifier);
		return result;
	}

	/**
	 * Set value of District_Province
	 * @param district_province
	 */
	public final void setDistrict_Province(address.proxies.Province district_province)
	{
		setDistrict_Province(getContext(), district_province);
	}

	/**
	 * Set value of District_Province
	 * @param context
	 * @param district_province
	 */
	public final void setDistrict_Province(com.mendix.systemwideinterfaces.core.IContext context, address.proxies.Province district_province)
	{
		if (district_province == null)
			getMendixObject().setValue(context, MemberNames.District_Province.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.District_Province.toString(), district_province.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return districtMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final address.proxies.District that = (address.proxies.District) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Address.District";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
