// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package address.proxies;

public class Province
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject provinceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Address.Province";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProvinceCode("ProvinceCode"),
		Province("Province"),
		IsActive("IsActive");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Province(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Address.Province"));
	}

	protected Province(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject provinceMendixObject)
	{
		if (provinceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Address.Province", provinceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Address.Province");

		this.provinceMendixObject = provinceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Province.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static address.proxies.Province initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return address.proxies.Province.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static address.proxies.Province initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new address.proxies.Province(context, mendixObject);
	}

	public static address.proxies.Province load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return address.proxies.Province.initialize(context, mendixObject);
	}

	public static java.util.List<address.proxies.Province> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<address.proxies.Province> result = new java.util.ArrayList<address.proxies.Province>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Address.Province" + xpathConstraint))
			result.add(address.proxies.Province.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProvinceCode
	 */
	public final java.lang.String getProvinceCode()
	{
		return getProvinceCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProvinceCode
	 */
	public final java.lang.String getProvinceCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProvinceCode.toString());
	}

	/**
	 * Set value of ProvinceCode
	 * @param provincecode
	 */
	public final void setProvinceCode(java.lang.String provincecode)
	{
		setProvinceCode(getContext(), provincecode);
	}

	/**
	 * Set value of ProvinceCode
	 * @param context
	 * @param provincecode
	 */
	public final void setProvinceCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String provincecode)
	{
		getMendixObject().setValue(context, MemberNames.ProvinceCode.toString(), provincecode);
	}

	/**
	 * @return value of Province
	 */
	public final java.lang.String getProvince()
	{
		return getProvince(getContext());
	}

	/**
	 * @param context
	 * @return value of Province
	 */
	public final java.lang.String getProvince(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Province.toString());
	}

	/**
	 * Set value of Province
	 * @param province
	 */
	public final void setProvince(java.lang.String province)
	{
		setProvince(getContext(), province);
	}

	/**
	 * Set value of Province
	 * @param context
	 * @param province
	 */
	public final void setProvince(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String province)
	{
		getMendixObject().setValue(context, MemberNames.Province.toString(), province);
	}

	/**
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive()
	{
		return getIsActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActive.toString());
	}

	/**
	 * Set value of IsActive
	 * @param isactive
	 */
	public final void setIsActive(java.lang.Boolean isactive)
	{
		setIsActive(getContext(), isactive);
	}

	/**
	 * Set value of IsActive
	 * @param context
	 * @param isactive
	 */
	public final void setIsActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.IsActive.toString(), isactive);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return provinceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final address.proxies.Province that = (address.proxies.Province) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Address.Province";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
