// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package address.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Address module
	public static void aCT_ActiveInactiveDistrict(IContext context, address.proxies.District _district)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("District", _district == null ? null : _district.getMendixObject());
			Core.execute(context, "Address.ACT_ActiveInactiveDistrict", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ActiveInactivePostcode(IContext context, address.proxies.Postcode _postcode)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Postcode", _postcode == null ? null : _postcode.getMendixObject());
			Core.execute(context, "Address.ACT_ActiveInactivePostcode", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ActiveInactiveProvince(IContext context, address.proxies.Province _province)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Province", _province == null ? null : _province.getMendixObject());
			Core.execute(context, "Address.ACT_ActiveInactiveProvince", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ActiveInactiveSubDistrict(IContext context, address.proxies.SubDistrict _subDistrict)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SubDistrict", _subDistrict == null ? null : _subDistrict.getMendixObject());
			Core.execute(context, "Address.ACT_ActiveInactiveSubDistrict", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void act_AddressTemplate_Import(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Address.Act_AddressTemplate_Import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_SaveDistrict(IContext context, address.proxies.District _district)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("District", _district == null ? null : _district.getMendixObject());
			Core.execute(context, "Address.ACT_SaveDistrict", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_SavePostcode(IContext context, address.proxies.Postcode _postcode)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Postcode", _postcode == null ? null : _postcode.getMendixObject());
			Core.execute(context, "Address.ACT_SavePostcode", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_SaveProvince(IContext context, address.proxies.Province _province)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Province", _province == null ? null : _province.getMendixObject());
			Core.execute(context, "Address.ACT_SaveProvince", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_SaveSubDistrict(IContext context, address.proxies.SubDistrict _subDistrict)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SubDistrict", _subDistrict == null ? null : _subDistrict.getMendixObject());
			Core.execute(context, "Address.ACT_SaveSubDistrict", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void act_Template_Import(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Address.Act_Template_Import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iNIT_District_Template(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Address.INIT_District_Template", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iNIT_PostCode_Template(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Address.INIT_PostCode_Template", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iNIT_SubDistrict_Template(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Address.INIT_SubDistrict_Template", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}